name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc:13
          - gcc:12
          - clang:17
          - clang:16
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@master
      - name: Setup
        run: |
          pip install -U conan
      - name: Build
        run: |
          conan create . --build=missing
