name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc:13
          - gcc:12
          - clang:17
          - clang:16
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Cache Conan Packages
        uses: actions/cache@main
        with:
          path: ~/.conan2/p/
          key: conan-${{ runner.os }}-${{ matrix.compiler }}
      - name: Setup
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install -U conan
          conan profile detect
      - name: Build
        run: |
          conan create . --build=missing
